# Generated by Django 3.2.8 on 2021-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
