# Generated by Django 3.2.8 on 2021-11-12 02:29

from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0002_create_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[msgserver.models.validate_key]),
        ),
    ]
